app/admin/__init__.py
# -*- encoding: utf-8 -*-


from flask import Blueprint

blueprint = Blueprint(
    'admin_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/admin/routes.py
# -*- encoding: utf-8 -*-

from app.admin import blueprint
from flask import render_template, redirect, url_for, request
from flask_login import login_required, current_user
from app import login_manager
from jinja2 import TemplateNotFound

#region  inputs

@blueprint.route('/manage/inputs')
@login_required
def inputs():
    return render_template('input/index.html', segment='index')

@blueprint.route('/manage/inputs/create')
@login_required
def inputs_create():
    return render_template('input/create.html', segment='index')

@blueprint.route('/manage/inputs/edit/<id>')
@login_required
def inputs_edit(id):
    return render_template('input/edit.html', segment='index', ids = id)

#region Outputs

@blueprint.route('/manage/outputs')
@login_required
def outputs(): 
    return render_template('output/index.html', segment='index')

@blueprint.route('/manage/outputs/create')
@login_required
def outputs_create(): 
    return render_template('output/create.html', segment='index')

@blueprint.route('/manage/outputs/edit/<id>')
@login_required
def outputs_edit(id):
    return render_template('output/edit.html', segment='index', ids = id)
  
#region  Data

@blueprint.route('/manage/data')
@login_required
def data():
    return render_template('data/index.html', segment='index')

@blueprint.route('/manage/data/create')
@login_required
def data_create():
    return render_template('data/create.html', segment='index')

@blueprint.route('/manage/data/edit/<id>')
@login_required
def data_edit(id):
    return render_template('data/edit.html', segment='index', ids = id)

#region manage

@blueprint.route('/manage')
@login_required
def manage(): 
    return render_template('manage.html', segment='index')


@blueprint.route('/engine/trainer')
@login_required
def trainer(): 
    return render_template('trainer.html', segment='index')
  
  
@blueprint.route('/engine/logger')
@login_required
def logger(): 
    return render_template('logger.html', segment='index')
  
  
@blueprint.route('/engine/report')
@login_required
def reporter(): 
    return render_template('reporter.html', segment='index')
  

app/admin/templates/data/create.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Add Data {% endblock title %}
{% block contentheader %}Add Data{% endblock %}

{% block stylesheets %}{% endblock stylesheets %}
{% block tools %}
{% endblock tools %}

{% block content %}

<!-- Hoverable rows start -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <div class="form-group">
                        <label for="idText">ID</label>
                        <input type="number" class="form-control" disabled name="idText" id="idText" v-model="id"
                            placeholder="Identifier (auto)">
                    </div>
                    <div class="form-group">
                        <label for="TitleText">Title</label>
                        <input type="text" class="form-control" name="TitleText" id="TitleText" v-model="text"
                            placeholder="Text">
                    </div>
                    <div class="form-group">
                        <label for="DescText">Description</label>
                        <input type="text" class="form-control" name="DescText" id="DescText" v-model="desc"
                            placeholder="Description">
                    </div>
                    <div class="form-group">
                        <label for="DataText">Data</label>
                        <input type="text" class="form-control" name="DataText" id="DataText" v-model="data"
                            placeholder="Data">
                    </div>
                    
                    <a class="btn btn-primary text-light"  @click="submit" role="button">Tambah</a>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

<script>
    const url = "{{ url_for('api_blueprint.data_api', _external=True) }}";

    const vm = new Vue({
        el: '#app',
        delimiters: ['[[', ']]'],
        data: {
            results: [],
            id: '',
            desc: '',
            data: '',
            text: ''
        },
        watch: {
            id: function (val) {
                if (val == "") {
                    $('#idText').removeClass('is-valid');
                    $('#idText').addClass('is-invalid');
                    return;
                }

                let data;
                axios.get(url + '/' + val).then(
                    function (response) {
                        data = response.data;
                        if (data.id == '-1') {
                            $('#idText').addClass('is-valid');
                            $('#idText').removeClass('is-invalid');
                            return true;
                        } else {
                            $('#idText').removeClass('is-valid');
                            $('#idText').addClass('is-invalid');
                            return false;
                        }
                    }
                )
            }
        },
        methods: {
            submit: function () {
                 
                data = {
                    "data": this.data,
                    "desc": this.desc,
                    "text": this.text
                };
                axios.post(url, data)
                window.location.href = "{{url_for('admin_blueprint.data')}}";
            }
        }

    });
</script>

{% endblock javascripts %}

app/admin/templates/data/edit.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Edit Data {% endblock title %}
{% block contentheader %}Edit Data{% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Hoverable rows start -->
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body">
          <div class="form-group">
            <label for="idText">ID</label>
            <input type="number" class="form-control" name="idText" id="idText" v-model="id"
              placeholder="Identifier (auto)">
          </div>
          <div class="form-group">
            <label for="TitleText">Title</label>
            <input type="text" class="form-control" name="TitleText" id="TitleText" v-model="text" placeholder="Text">
          </div>
          <div class="form-group">
            <label for="DescText">Description</label>
            <input type="text" class="form-control" name="DescText" id="DescText" v-model="desc"
              placeholder="Description">
          </div>
          <div class="form-group">
            <label for="DataText">Data</label>
            <input type="text" class="form-control" name="DataText" id="DataText" v-model="data" placeholder="Data">
          </div>

          <a class="btn btn-primary text-light" @click="submit" role="button">Ubah</a>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

<script>
  const id = window.location.pathname.split("/").pop();
  console.log('id : ' + id);
  const url = "{{ url_for('api_blueprint.data_api', _external=True) }}/" + id;

  const vm = new Vue({
    el: '#app',
    delimiters: ['[[', ']]'],
    created: function () {
      axios
        .get(url)
        .then(res => {
          this.loading = false;
          this.results = res.data;
          console.log(this.results);
          this.id = this.results.id;
          this.desc = this.results.desc;
          this.data = this.results.data;
          this.text = this.results.text;
        });

    },
    data: {
      results: [],
      id: '',
      desc: '',
      data: '',
      text: ''
    },
    computed: {
      idValid: function () {
        return id != 0;
      }
    },
    methods: {
      submit: function () {

        data = {
          "data": this.data,
          "desc": this.desc,
          "text": this.text
        };
        axios.put(url, data)
        window.location.href = "{{url_for('admin_blueprint.data')}}";
      }
    }

  });
</script>

{% endblock javascripts %}

app/admin/templates/data/index.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Data {% endblock title %}
{% block contentheader %}Data{% endblock %}

{% block stylesheets %}{% endblock stylesheets %}
{% block tools %}
<a class="btn btn-primary " href="{{ url_for('admin_blueprint.data_create') }}" role="button">Tambah</a>
{% endblock tools %}

{% block content %}

<!-- Hoverable rows start -->
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body">
          <p v-if="loading">Loading...</p>
          <div v-else class="table-responsive table-sm">
            <table class="table table-bordered table-hover mb-0" id="table">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Text</th>
                  <th>Description</th>
                  <th>Data</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(result, index) in results" :key="index">
                  <td class="text-bold-500">[[ result.id ]] </td>
                  <td>[[ result.text ]]</td>
                  <td>[[ result.desc ]]</td>
                  <td>[[ result.data ]]</td>
                  <td>
                    <button type="button" name="bEdit" id="bEdit" @click="edit_data($event)" :value="result.id"
                      class="btn btn-outline-primary btn-xs">
                      <i data-feather="edit-1"></i>Edit
                    </button>
                    <button type="button" name="bEdit" id="bEdit" @click="delete_data($event)" :value="result.id"
                      class="btn btn-outline-primary btn-xs">
                      <i data-feather="trash"></i>Delete
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <p v-if="error">{{ error }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
 

<div v-if="loading" class="modal" id="loadingModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-dialog-centered d-flex justify-content-center " role="document">
      <div class="card ">
        <div class="card-body">
          <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

<script>


</script>

<script src="{{ url_for('static',  filename='assets/js/table.js')}}"></script>

<script>
  async function SetTable() {
    // await new Promise(r => setTimeout(r, 1));

    tb = $('#table').DataTable({
      "paging": true,
      "searching": true,
      "ordering": true,
      "retrieve": true,
      "autoWidth": false,
      "responsive": true,
      "oLanguage": {
        "sEmptyTable": "Tidak ada data yang tersedia pada tabel ini",
        "sProcessing": "Sedang memproses...",
        "sLengthMenu": "Tampilkan _MENU_ entri",
        "sZeroRecords": "Tidak ditemukan data yang sesuai",
        "sInfo": "Menampilkan _START_ sampai _END_ dari _TOTAL_ entri",
        "sInfoEmpty": "Menampilkan 0 sampai 0 dari 0 entri",
        "sInfoFiltered": "(disaring dari _MAX_ entri keseluruhan)",
        "sInfoPostFix": "",
        "sSearch": "Cari:",
        "sUrl": "",
        "oPaginate": {
          "sFirst": "Pertama",
          "sPrevious": "Sebelumnya",
          "sNext": "Selanjutnya",
          "sLast": "Terakhir"
        }
      }
    });
    tb.draw();

  }
  // const url = "https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH&tsyms=USD,EUR";
  const url = "{{ url_for('api_blueprint.data_api', _external=True) }}";

  const vm = new Vue({
    el: '#app',
    delimiters: ['[[', ']]'],
    data: {
      loading: false,
      results: [],
      error: ""
    },
    created: function () {
      this.load_data();
    },
    mounted: function () {
      SetTable();

    },
    methods: {
      load_data: function () {
        this.loading = true;
        axios
          .get(url)
          .then(res => {
            this.loading = false;
            this.results = res.data;
          });
      },
      edit_data: function (e) {
        const id = e.target.value;
        const url = "{{ url_for('admin_blueprint.data') }}/edit/" + id;
        window.location.href = url;
      },
      delete_data: function (e) {
        const id = e.target.value;
        axios.delete(url + '/' + id);
        this.load_data();

        window.location.href = "{{ url_for('admin_blueprint.data') }}";
      }
    }
  });
</script>

{% endblock javascripts %}

app/admin/templates/input/create.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Add Input Variable {% endblock title %}
{% block contentheader %}Add Input Variable{% endblock %}

{% block stylesheets %}{% endblock stylesheets %}
{% block tools %}
{% endblock tools %}

{% block content %}

<!-- Hoverable rows start -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <div class="form-group">
                        <label for="idText">ID</label>
                        <input type="number" class="form-control" disabled name="idText" id="idText" v-model="id"
                            placeholder="Identifier (auto)">
                    </div>
                    <div class="form-group">
                        <label for="TitleText">Title</label>
                        <input type="text" class="form-control" name="TitleText" id="TitleText" v-model="text"
                            placeholder="Text">
                    </div>
                    <div class="form-group">
                        <label for="DescText">Description</label>
                        <input type="text" class="form-control" name="DescText" id="DescText" v-model="desc"
                            placeholder="Description">
                    </div>
                    <div class="form-group">
                        <label for="DataText">Data</label>
                        <input type="text" class="form-control" name="DataText" id="DataText" v-model="data"
                            placeholder="Data">
                    </div>
                    
                    <a class="btn btn-primary text-light"  @click="submit" role="button">Tambah</a>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

<script>
    const url = "{{ url_for('api_blueprint.input_api', _external=True) }}";

    const vm = new Vue({
        el: '#app',
        delimiters: ['[[', ']]'],
        data: {
            results: [],
            id: '',
            desc: '',
            data: '',
            text: ''
        },
        watch: {
            id: function (val) {
                if (val == "") {
                    $('#idText').removeClass('is-valid');
                    $('#idText').addClass('is-invalid');
                    return;
                }

                let data;
                axios.get(url + '/' + val).then(
                    function (response) {
                        data = response.data;
                        if (data.id == '-1') {
                            $('#idText').addClass('is-valid');
                            $('#idText').removeClass('is-invalid');
                            return true;
                        } else {
                            $('#idText').removeClass('is-valid');
                            $('#idText').addClass('is-invalid');
                            return false;
                        }
                    }
                )
            }
        },
        methods: {
            submit: function () {
                 
                data = {
                    "data": this.data,
                    "desc": this.desc,
                    "text": this.text
                };
                axios.post(url, data)
                window.location.href = "{{url_for('admin_blueprint.inputs')}}";
            }
        }

    });
</script>

{% endblock javascripts %}

app/admin/templates/input/edit.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Edit Input Variable {% endblock title %}
{% block contentheader %}Edit Input Variable{% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Hoverable rows start -->
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body">
          <div class="form-group">
            <label for="idText">ID</label>
            <input type="number" class="form-control" name="idText" id="idText" v-model="id"
              placeholder="Identifier (auto)">
          </div>
          <div class="form-group">
            <label for="TitleText">Title</label>
            <input type="text" class="form-control" name="TitleText" id="TitleText" v-model="text" placeholder="Text">
          </div>
          <div class="form-group">
            <label for="DescText">Description</label>
            <input type="text" class="form-control" name="DescText" id="DescText" v-model="desc"
              placeholder="Description">
          </div>
          <div class="form-group">
            <label for="DataText">Data</label>
            <input type="text" class="form-control" name="DataText" id="DataText" v-model="data" placeholder="Data">
          </div>

          <a class="btn btn-primary text-light" @click="submit" role="button">Ubah</a>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

<script>
  const id = window.location.pathname.split("/").pop();
  console.log('id : ' + id);
  const url = "{{ url_for('api_blueprint.input_api', _external=True) }}/" + id;

  const vm = new Vue({
    el: '#app',
    delimiters: ['[[', ']]'],
    created: function () {
      axios
        .get(url)
        .then(res => {
          this.loading = false;
          this.results = res.data;
          console.log(this.results);
          this.id = this.results.id;
          this.desc = this.results.desc;
          this.data = this.results.data;
          this.text = this.results.text;
        });

    },
    data: {
      results: [],
      id: '',
      desc: '',
      data: '',
      text: ''
    },
    computed: {
      idValid: function () {
        return id != 0;
      }
    },
    methods: {
      submit: function () {

        data = {
          "data": this.data,
          "desc": this.desc,
          "text": this.text
        };
        axios.put(url, data)
        window.location.href = "{{url_for('admin_blueprint.inputs')}}";
      }
    }

  });
</script>

{% endblock javascripts %}

app/admin/templates/input/index.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Features {% endblock title %}
{% block contentheader %}Features{% endblock %}

{% block stylesheets %}{% endblock stylesheets %}
{% block tools %}
<a class="btn btn-light" href="{{ url_for('admin_blueprint.inputs_create') }}" role="button">
  <i data-feather="download"></i>
</a>
<a class="btn btn-light" href="{{ url_for('admin_blueprint.inputs_create') }}" role="button">
  <i data-feather="upload"></i>
</a>
<a class="btn btn-success " href="{{ url_for('admin_blueprint.inputs_create') }}" role="button">Add Feature</a>
{% endblock tools %}

{% block content %}

<!-- Hoverable rows start -->

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body p-0 border-0">
          <div class="table-responsive table-sm border-0" style="min-height: 65vh;">
            <table class="table border-0 table-hover " id="table">
              <thead class="">
                <tr>
                  <th class="text-center align-middle p-0 m-0" width="30">
                    <input type="checkbox" v-model="selectAll">
                  </th>
                  <th>No</th>
                  <th>Text</th>
                  <th>Description</th>
                  <th>Data</th>
                  <th width="30">Action</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(result, index) in results" :key="index" :value="result.id">
                  <td  class="text-center align-middle p-0 m-0"><input type="checkbox" v-model="selected"
                      :value="result.id" number></td>
                  <td>[[ result.id ]] </td>
                  <td>[[ result.text ]]</td>
                  <td>[[ result.desc ]]</td>
                  <td>[[ result.data ]]</td>
                  <td class="p-0">
                    <div class="btn-group">
                      <button class="btn-sm btn" type="button" data-reference="parent" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i data-feather="more-horizontal"></i>
                      </button>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" @click="edit_data(result.id)"> <i data-feather="edit-1"></i>Edit</a>
                        <a class="dropdown-item" @click="delete_data(result.id)"><i data-feather="trash"></i>Delete</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Export</a>
                      </div>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <p v-if="error">{{ error }}</p>
        </div>
      </div>
      <div v-if="loading" class="overlay" style="color:343a40;">
        <div class="spinner-border" role="status">
          <span class="sr-only">Loading...</span>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}


<script src="{{ url_for('static',  filename='assets/js/table.js')}}"></script>

<script>
  // const url = "https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH&tsyms=USD,EUR";
  const api = "{{ url_for('api_blueprint.input_api', _external=True) }}";

  const vm = new Vue({
    el: '#app',
    delimiters: ['[[', ']]'],
    data: {
      loading: true,
      results: [],
      error: "",
      selected: []
    },
    computed: {
      selectAll: {
        get: function () {
          if (this.results && this.results.length > 0) {
            let allChecked = true;

            for (const result of this.results) {
              if (!this.selected.includes(result.id)) {
                allChecked = false;
              }

              if (!allChecked) break;
            }
            return allChecked;
          }

          return false;
        },
        set: function (value) {
          var selected = [];

          if (value) {
            this.results.forEach(function (result) {
              selected.push(result.id);
            });
          }

          this.selected = selected;
        }
      }
    },
    created: function () {
      this.load_data();
    },
    mounted: function () {

    },
    methods: {
      load_data: function () {
        this.loading = true;
        axios
          .get(api)
          .then(res => {
            this.results = res.data;
            console.log('data loaded..')
            this.loading = false;
        });

      },
      edit_data: function (e) {
        const id = e;
        const url = "{{ url_for('admin_blueprint.inputs') }}/edit/" + id;
        window.location.href = url;
      },
      delete_data: function (e) {
        const id = e;
        axios.delete(api + '/' + id);
        this.load_data();
        window.location.href = "{{ url_for('admin_blueprint.inputs') }}";
      }
    }
  });
</script>

{% endblock javascripts %}

app/admin/templates/logger.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Logger {% endblock title %}
{% block contentheader %}Logger{% endblock %}
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Hoverable rows start -->
<div class="row" id="table-hover-row">
    <div class="col-12">
      <div class="card">
    
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
 

{% endblock javascripts %}

app/admin/templates/manage.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Manage {% endblock title %}
{% block contentheader %}Manage{% endblock %}
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Hoverable rows start -->
<div class="row" id="table-hover-row">
    <div class="col-12">
      <div class="card">
      
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
 
{% endblock javascripts %}

app/admin/templates/output/index.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Output Variables {% endblock title %}
{% block contentheader %}Output Variables{% endblock %}

{% block stylesheets %}{% endblock stylesheets %}
{% block tools %}
<a class="btn btn-primary " href="{{ url_for('admin_blueprint.outputs_create') }}" role="button">Tambah</a>
{% endblock tools %}

{% block content %}

<!-- Hoverable rows start -->
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body">
          <p v-if="loading">Loading...</p>
          <div v-else class="table-responsive table-sm">
            <table class="table table-bordered table-hover mb-0" id="table">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Text</th>
                  <th>Description</th>
                  <th>Data</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(result, index) in results" :key="index">
                  <td class="text-bold-500">[[ result.id ]] </td>
                  <td>[[ result.text ]]</td>
                  <td>[[ result.desc ]]</td>
                  <td>[[ result.data ]]</td>
                  <td>
                    <button type="button" name="bEdit" id="bEdit" @click="edit_data($event)" :value="result.id"
                      class="btn btn-outline-primary btn-xs">
                      <i data-feather="edit-1"></i>Edit
                    </button>
                    <button type="button" name="bEdit" id="bEdit" @click="delete_data($event)" :value="result.id"
                      class="btn btn-outline-primary btn-xs">
                      <i data-feather="trash"></i>Delete
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <p v-if="error">{{ error }}</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div v-if="loading" class="modal" id="loadingModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-dialog-centered d-flex justify-content-center " role="document">
      <div class="card ">
        <div class="card-body">
          <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

<script>


</script>

<script src="{{ url_for('static',  filename='assets/js/table.js')}}"></script>

<script>
  async function SetTable() {
    // await new Promise(r => setTimeout(r, 1));

    tb = $('#table').DataTable({
      "paging": true,
      "searching": true,
      "ordering": true,
      "retrieve": true,
      "autoWidth": false,
      "responsive": true,
      "oLanguage": {
        "sEmptyTable": "Tidak ada data yang tersedia pada tabel ini",
        "sProcessing": "Sedang memproses...",
        "sLengthMenu": "Tampilkan _MENU_ entri",
        "sZeroRecords": "Tidak ditemukan data yang sesuai",
        "sInfo": "Menampilkan _START_ sampai _END_ dari _TOTAL_ entri",
        "sInfoEmpty": "Menampilkan 0 sampai 0 dari 0 entri",
        "sInfoFiltered": "(disaring dari _MAX_ entri keseluruhan)",
        "sInfoPostFix": "",
        "sSearch": "Cari:",
        "sUrl": "",
        "oPaginate": {
          "sFirst": "Pertama",
          "sPrevious": "Sebelumnya",
          "sNext": "Selanjutnya",
          "sLast": "Terakhir"
        }
      }
    });
    tb.draw();

  }
  // const url = "https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH&tsyms=USD,EUR";
  const url = "{{ url_for('api_blueprint.output_api', _external=True) }}";

  const vm = new Vue({
    el: '#app',
    delimiters: ['[[', ']]'],
    data: {
      loading: false,
      results: [],
      error: ""
    },
    created: function () {
      this.load_data();
    },
    mounted: function () {
      SetTable();

    },
    methods: {
      load_data: function () {
        this.loading = true;
        axios
          .get(url)
          .then(res => {
            this.loading = false;
            this.results = res.data;
          });
      },
      edit_data: function (e) {
        const id = e.target.value;
        const url = "{{ url_for('admin_blueprint.outputs') }}/edit/" + id;
        window.location.href = url;
      },
      delete_data: function (e) {
        const id = e.target.value;
        axios.delete(url + '/' + id);
        this.load_data();

        window.location.href = "{{ url_for('admin_blueprint.outputs') }}";
      }
    }
  });
</script>

{% endblock javascripts %}

app/admin/templates/reporter.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Report {% endblock title %}
{% block contentheader %}Report{% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Hoverable rows start -->
<div class="row" id="table-hover-row">
    <div class="col-12">
      <div class="card">
       
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
 
{% endblock javascripts %}

app/admin/templates/trainer.html
{% extends 'layouts/layout-base.html' %}


{% block title %} Trainer {% endblock title %}
{% block contentheader %}Trainer{% endblock %}

 
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Hoverable rows start -->
<div class="row" id="table-hover-row">
    <div class="col-12">
      <div class="card">
     
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %} 

{% endblock javascripts %}