app/base/models.py
# -*- encoding: utf-8 -*-

from flask_login import UserMixin
from app import db, login_manager
from app.base.util import hash_pass

from sqlalchemy import Binary, Column, Integer, String

class User(db.Model, UserMixin):

    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    email = Column(String, unique=True)
    username = Column(String, unique=True)
    fullname = Column(String)
    password = Column(Binary)
    locale  =  Column(String)
    timezone  =  Column(String)
    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-


from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('errors/page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('errors/page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('errors/page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('errors/page-500.html'), 500

app/base/templates/accounts/login.html
{% extends 'layouts/layout-base-full.html' %}

{% block title %} Login {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="auth-logo">
    <a href="{{ url_for('home_blueprint.index') }}">
        <img src="{{ url_for('static', filename='favicon.ico') }}" height="64" class='mb-4'>
    </a>
</div>

<div class="card">
    <div class="card-body">

        <div class="text-center mb-5">
            <h3>Masuk</h3>
            <span class="mb-0 text-muted text-center">
                {% if msg %}
                {{ msg | safe }}
                {% else %}
                Akun default: admin / `
                {% endif %}
            </span>
        </div>

        <form role="form" method="post" action="">
            {{ form.hidden_tag() }}
            <div class="input-group mb-3">
                {{ form.username(placeholder="Username", class="form-control") }}
                <div class="input-group-append">
                    <div class="input-group-text">
                        <i data-feather="user"></i>
                    </div>
                </div>
            </div>
            <div class="input-group mb-3">
                {{ form.password(placeholder="Password", class="form-control", type="password") }}

                <div class="input-group-append">
                    <div class="input-group-text">
                        <i data-feather="key"></i>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-8">
                    <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" class="form-check-input" name="" id="" value="checkedValue" checked>
                            Ingat saya
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-4">
                    <button type="submit" name="login" class="btn btn-primary btn-block">Masuk</button>
                </div>
                <!-- /.col -->
            </div>
            <br />
            <div class="float-right">
                <a href="{{ url_for('base_blueprint.register') }}">Belum punya akun?</a>
            </div>
        </form>

    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/accounts/register.html
{% extends 'layouts/layout-base-full.html' %}

{% block title %} Register {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="card pt-4">
  <div class="card-body">
    <div class="text-center mb-5">
      <img src="{{ url_for('static', filename='favicon.ico') }}" height="48" class='mb-4'>
      <h3>Sign Up</h3>

      <span class="mb-0 text-muted text-center">
        {% if msg %}
        {{ msg | safe }}
        {% else %}
        Add your credentials
        {% endif %}
      </span>
    </div>
    <form role="form" method="post" action="">

      {{ form.hidden_tag() }}

      <div class="form-group">
        {{ form.username(placeholder="Username", class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.email(placeholder="Email", class="input form-control", type="email") }}
      </div>
      <div class="form-group">
        {{ form.password(placeholder="Password", class="form-control", type="password") }}
      </div>
      <br />
      <div class="form-group text-left">
        <div class="checkbox checkbox-fill d-inline">
          <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
          <label for="checkbox-fill-a1" class="cr"> Agree with <a href="#">terms</a></label>
        </div>
      </div>
      <div class="clearfix">
        <button type="submit" name="register" class="btn btn-primary">Register</button>
      </div>
      <br />
      <a href="{{ url_for('base_blueprint.login') }}">Have an account? Login</a>
    </form>
  </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/includes/footer.html
<footer class="main-footer text-sm py-2">
  <div class="float-right d-none d-sm-block m-0 p-0">
    <a  data-widget="control-sidebar" href="#" class="btn btn-light m-0 p-1">
    <b>Version</b> 0.1</a>
  </div>
  <strong>Copyright &copy; 2020 <a href="http://hafari.id">hafari.id</a>.</strong> All rights reserved.
</footer>

app/base/templates/includes/navigation.html
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
          <li class="nav-item">
              <a class="nav-link" data-widget="pushmenu" href="#" role="button">
                  <i data-feather="menu"></i></a>
          </li>
          <!-- <li class="nav-item d-none d-sm-inline-block">
              <a href="{{ url_for('home_blueprint.index') }}" class="nav-link">Dashboard</a>
          </li> -->
      </ul>

      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">

          {% with messages = get_flashed_messages() %}
          <li class="nav-item dropdown">
              <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
                  <i data-feather="bell"></i>
                  {% if messages %}
                  <span class="badge badge-warning navbar-badge">{{messages|count}}</span>

                  {% endif %}
              </a>
              <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">
                  <span class="dropdown-item dropdown-header">Notifications</span>
                  <div class="dropdown-divider"></div>

                  {% if messages %}
                  {% for message in messages %}
                  <a href="#" class="dropdown-item">
                      <i data-feather="info"></i> {{ message }}.
                  </a>
                  {% endfor %}
                  {% else %}
                  <a href="#" class="dropdown-item">
                      <i data-feather="check"></i> Nothing here.
                  </a>
                  {% endif %}
                  <div class="dropdown-divider"></div>

                  <a href="#" class="dropdown-item dropdown-footer">Show All Notifications</a>
              </div>
          </li>
          {% endwith %}
          <li class="nav-item dropdown user-menu">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <span class="d-none d-md-inline">Hi, {{ current_user.username }}</span>
              </a>
              <ul class="dropdown-menu dropdown-menu-right" style="left: inherit;right: 0px;">
                  <!-- User image -->
                  <li class="user-header bg-light" style=" height: 80px; ">
                      <p>
                          {{ current_user.username }}
                          <small>
                              {{ current_user.email }}
                          </small>
                      </p>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                      <a href="/profile.html" class="btn btn-default btn-flat">Settings</a>
                      <a href="{{ url_for('base_blueprint.logout') }}" class="btn btn-default btn-flat float-right">Sign
                          out</a>
                  </li>
              </ul>
          </li>

      </ul>
  </nav>

app/base/templates/includes/scripts.html
<script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/js/adminlte.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/js/datatables.min.js') }}"></script>

<script src="{{ url_for('static', filename='assets/js/vue.js') }}"></script>
<script src="{{ url_for('static', filename='assets/js/axios.min.js') }}"></script>
<script>
  feather.replace({width: '1em', height: '1em'})
</script>

app/base/templates/includes/sidenav.html
{% macro nav_link(endpoint, text, icon, notify) %}
{%- if request.endpoint is not none -%}
{%- if request.endpoint.endswith(endpoint) -%}
{% set isactive = 'active' %}
{% set url_end = '#' %}
{%- else -%}
{% set isactive = '' %}
{% set url_end = url_for(endpoint) %}
{%- endif -%}
{% set isenable = '' %}
{%- else -%}
{% set isenable = 'disable' %}
{%- endif -%}

<li class="nav-item ">
  <a href="{{ url_end }}" class="nav-link {{isactive}} {{isenable}}">
    <i class="nav-icon" data-feather="{{icon}}" width="20" height="20"></i>
    <p>
      <span class="align-middle">{{ text | title }}</span>
      {% if notify %}
      <span class="right badge badge-danger">1</span>
      {% endif %}
    </p>
  </a>
</li>

{% endmacro %}

{% macro nav_header(text) %}
<li class="nav-header">{{text}}</li>
{% endmacro %}

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-2">

  <a href="{{ url_for('home_blueprint.index') }}" class="brand-link">
    <img class="brand-image " src="{{ url_for('static', filename='favicon.ico') }}" class='mb-4'>
    <span class="brand-text font-weight-light">SIPTA</span>
  </a>

  <div class="sidebar">
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false"> 
        {{ nav_link('home_blueprint.index','Dashboard', 'home') }}
        {{ nav_link('home_blueprint.help','Help', 'help-circle') }}

        {{ nav_header('Administration')}}

        {{ nav_link('admin_blueprint.inputs','Features', 'layout') }}
        {{ nav_link('admin_blueprint.outputs','Classes', 'grid') }}
        {{ nav_link('admin_blueprint.data','Data', 'layers') }}
        {{ nav_link('admin_blueprint.manage','Statistics', 'file-plus') }}

        {{ nav_header('Training')}}

        {{ nav_link('admin_blueprint.trainer','Trainer', 'layers', True) }}
        {{ nav_link('admin_blueprint.logger','Logger', 'layers') }}
        {{ nav_link('admin_blueprint.reporter','Report', 'layers') }}

      </ul>
    </nav>
  </div>
</aside>

<aside class="control-sidebar control-sidebar-light"> 
  <div class="p-3"> 
    
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

      </ul>
    </nav>
  </div>
</aside>

app/base/templates/layouts/base-fullscreen.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>
    SIPTA - {% block title %} {% endblock %}
  </title>

  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css"> 
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  
  <script src="https://unpkg.com/feather-icons"></script>
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="hold-transition auth-page"> 

  <div class="auth-box">
    {% block content %}{% endblock content %} 
  </div>
    
  {% include "includes/scripts.html" %}
 
  {% block javascripts %}{% endblock javascripts %}
     
</body>

</html>

app/base/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>
    SIPTA - {% block title %} {% endblock %}
  </title>

  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <link rel="stylesheet" href="{{ url_for('static', filename='/assets/css/adminlte.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='/assets/css/datatables.min.css') }}">

  <script src="https://unpkg.com/feather-icons"></script>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="hold-transition sidebar-mini layout-footer-fixed layout-sidebar-fixed ">
  <div class="wrapper" id="app">

    {% include "includes/navigation.html" %}

    {% include "includes/sidenav.html" %}

    <div class="content-wrapper">

      <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-1">
            <div class="col-sm-6">
              <h4>{% block contentheader %} {% endblock %}</h4>
            </div>
            <div class="col-sm-6">

            </div>
          </div>
        </div>
      </section>
      <section class="content">
        <div class="container-fluid"> 
          {% block content %}{% endblock content %} 
        </div>

      </section>
    </div>
    {% include 'includes/footer.html' %}
  </div>

  {% include "includes/scripts.html" %}

  {% block javascripts %}{% endblock javascripts %}
</body>

</html>

app/base/templates/layouts/layout-base-full.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>
    SIPTA - {% block title %}{% endblock %}
  </title>

  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css"> 
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <script src="https://unpkg.com/feather-icons"></script>

  {% block stylesheets %}{% endblock stylesheets %} 
  <meta name="theme-color" content="{% block themecolor %}#4b545c{% endblock themecolor %}">
  <style>
    body {overflow-y:scroll;}
  </style>
</head>

<body class="hold-transition auth-page"  > 

  <div class="auth-box">
    {% block content %}{% endblock content %} 
  </div>
    
  {% include "includes/scripts.html" %}
 
  {% block javascripts %}{% endblock javascripts %}
     
</body>

</html>

app/base/templates/layouts/layout-base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>
    SIPTA - {% block title %} {% endblock %}
  </title>

  <script src="{{ url_for('static', filename='assets/js/feather.min.js') }}"></script>
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/adminlte.min.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/datatables.min.css') }}">


  {% block stylesheets %}{% endblock stylesheets %}

  <meta name="theme-color" content="{% block themecolor %}#4b545c{% endblock themecolor %}">
  <style>
    body {
      overflow-y: scroll;
    }
  </style>  
</head>

<body class="hold-transition sidebar-mini layout-footer-fixed layout-sidebar-fixed"> 
  <div class="wrapper" id="app"> 

    {% include "includes/navigation.html" %}

    {% include "includes/sidenav.html" %}

    <div class="content-wrapper">

      <section class="content-header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6 py-1 px-2">
              <h4 class="m-0 align-middle">{% block contentheader %} {% endblock %}</h4>
            </div>
            <div class="col-sm-6 align-right">
              <div class="float-right">
                {% block tools %} {% endblock %}</div>
            </div>
          </div>
        </div>
      </section>
      <section class="content">
        <div class="container-fluid">
          {% block content %}{% endblock content %}
        </div>

      </section>
    </div>
    {% include 'includes/footer.html' %}
  </div>

  {% include "includes/scripts.html" %}

  {% block javascripts %}{% endblock javascripts %}
</body>

</html>